### ISSUE TITLE
chown www-data var dir error

### ISSUE THREAD

**Issue by litan1106** [sherifabdlnaby/symdocker#4]
chown: var: No such file or directory

[https://github.com/sherifabdlnaby/symdocker/blob/master/docker/.scripts/dev/docker-dev-install#L5](url)

**Comment by hacfi** [comment]
Your project doesn't have a `var` directory: either it's not a standard Symfony app (based on the skeleton or standard edition). Or maybe it's an old Symfony app which still uses `app/var` instead of `app`. OR you have the Symfony app or the symdocker files in a subdirectory. In any case: without more details we won't be able to help you.

**Comment by litan1106** [comment]
I fixed it with
chown -R www-data:www-data /var/www
